services:
  - type: web
    name: cart-app-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd cartapp && python manage.py collectstatic --noinput
    startCommand: cd cartapp && gunicorn cartapp.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: 'localhost,127.0.0.1,cart-app-backend-2ubt.onrender.com'
